"""Add scraped_events table

Revision ID: 71dd582bd7f1
Revises: 36843084c8fc
Create Date: 2025-07-21 17:46:03.812551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71dd582bd7f1'
down_revision: Union[str, Sequence[str], None] = '36843084c8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'start_date', name='_title_start_date_uc')
    )
    op.create_index(op.f('ix_scraped_events_id'), 'scraped_events', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_events_start_date'), 'scraped_events', ['start_date'], unique=False)
    op.create_index(op.f('ix_scraped_events_title'), 'scraped_events', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_events_title'), table_name='scraped_events')
    op.drop_index(op.f('ix_scraped_events_start_date'), table_name='scraped_events')
    op.drop_index(op.f('ix_scraped_events_id'), table_name='scraped_events')
    op.drop_table('scraped_events')
    # ### end Alembic commands ###
